#!/usr/bin/env sh
curl -s http://getcomposer.org/installer | php
php composer.phar create-project symfony/framework-standard-edition vagrant.dev
cd vagrant.dev

setfacl -R -m u:www-data:rwx app/cache app/logs
setfacl -R -d -m u:www-data:rwx app/cache app/logs

setfacl -R -m u:vagrant:rwx app/cache app/logs
setfacl -R -d -m u:vagrant:rwx app/cache app/logs

setfacl -R -m mask:rwx app/cache app/logs
setfacl -R -d -m mask:rwx app/cache app/logs

sed -i 's/\(::1\)/10.0.100.1/' web/app_dev.php
sed -i 's/\(::1\)/10.0.100.1/' web/config.php

exit 0
